AspNetCoreMVC/AspNetCoreMVC_Assignment2/Models/ErrorViewModel.cs
namespace AspNetCoreMVC_Assignment2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Models/PersonCreateModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreMVC_Assignment2.Models;
public class PersonCreateModel
{
    [DisplayName("First Name")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? FirstName { get; set; }

    [DisplayName("Last Name")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? LastName { get; set; }

    [DisplayName("Gender")]
    public string? Gender { get; set; }

    [DisplayName("Date Of Birth")]
    [Required(ErrorMessage = "{0} is required!")]
    public DateTime DateOfBirth { get; set; }

    [DisplayName("Phone Number")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? PhoneNumber { get; set; }

    [DisplayName("Birth Place")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? BirthPlace { get; set; }
}

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Models/PersonModel.cs
namespace AspNetCoreMVC_Assignment2.Models;

public class PersonModel
{
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? Gender { get; set; }
    public DateTime DateOfBirth { get; set; }
    public string? PhoneNumber { get; set; }
    public string? BirthPlace { get; set; }
    public Boolean IsGraduated { get; set; }
    public int Age
    {
        get
        {
            return DateTime.Now.Year - DateOfBirth.Year;
        }
    }
    public string FullName
    {
        get
        {
            return $"{LastName} {FirstName}";
        }
    }
}

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Models/PersonUpdateModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreMVC_Assignment2.Models;
public class PersonUpdateModel
{
    [DisplayName("First Name")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? FirstName { get; set; }

    [DisplayName("Last Name")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? LastName { get; set; }

    [DisplayName("Gender")]
    public string? Gender { get; set; }

    [DisplayName("Date Of Birth")]
    [Required(ErrorMessage = "{0} is required!")]
    public DateTime DateOfBirth { get; set; }

    [DisplayName("Phone Number")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? PhoneNumber { get; set; }

    [DisplayName("Birth Place")]
    [Required(ErrorMessage = "{0} is required!")]
    public string? BirthPlace { get; set; }

    public int Index { get; set; }
}

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreMVC_Assignment2.Models;

namespace AspNetCoreMVC_Assignment2.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Controllers/RookiesController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreMVC_Assignment2.Models;

namespace AspNetCoreMVC_Assignment2.Controllers;
public class RookiesController : Controller
{
    private static List<PersonModel> _people = new List<PersonModel>()
    {
        new PersonModel()
        {
            FirstName = "Truong",
            LastName = "Nguyen Cong",
            Gender = "Male",
            DateOfBirth = new DateTime(2002, 07, 22),
            PhoneNumber = "0123456789",
            BirthPlace = "Ha Noi",
            IsGraduated = true
        },
        new PersonModel()
        {
            FirstName = "Tai",
            LastName = "Pham Tien",
            Gender = "Female",
            DateOfBirth = new DateTime(2000, 02, 15),
            PhoneNumber = "0123456789",
            BirthPlace = "Ha Noi",
            IsGraduated = false
        },
        new PersonModel()
        {
            FirstName = "Than",
            LastName = "Nguyen Van",
            Gender = "Others",
            DateOfBirth = new DateTime(2000, 10, 08),
            PhoneNumber = "0123456789",
            BirthPlace = "Ha Noi",
            IsGraduated = true
            },
        new PersonModel()
        {
            FirstName = "Vinh",
            LastName = "Nguyen",
            Gender = "Male",
            DateOfBirth = new DateTime(2002, 08, 07),
            PhoneNumber = "0123456789",
            BirthPlace = "Ho Chi Minh",
            IsGraduated = false
        },
        new PersonModel()
        {
            FirstName = "Minh",
            LastName = "Do Tran",
            Gender = "Female",
            DateOfBirth = new DateTime(1998, 07, 22),
            PhoneNumber = "0123456789",
            BirthPlace = "Da Nang",
            IsGraduated = true
        },
        new PersonModel()
        {
            FirstName = "Tran Thi",
            LastName = "Thao",
            Gender = "Female",
            DateOfBirth = new DateTime(1998, 05, 17),
            PhoneNumber = "0123456789",
            BirthPlace = "Hai Phong",
            IsGraduated = false
        }
    };

    private readonly ILogger<RookiesController> _logger;

    public RookiesController(ILogger<RookiesController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View(_people);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(PersonCreateModel model)
    {
        if (ModelState.IsValid)
        {
            var person = new PersonModel
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Gender = model.Gender,
                DateOfBirth = model.DateOfBirth,
                PhoneNumber = model.PhoneNumber,
                BirthPlace = model.BirthPlace,
                IsGraduated = false
            };

            _people.Add(person);

            return RedirectToAction("Index");
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult Edit(int index)
    {
        if (index >= 0 && index < _people.Count)
        {
            var person = _people[index];
            var model = new PersonUpdateModel
            {
                FirstName = person.FirstName,
                LastName = person.LastName,
                Gender = person.Gender,
                DateOfBirth = person.DateOfBirth,
                PhoneNumber = person.PhoneNumber,
                BirthPlace = person.BirthPlace,
            };
            ViewData["Index"] = index;
            return View(model);
        }
        return View();
    }

    [HttpPost]
    public IActionResult Update(int index, PersonUpdateModel model)
    {
        if (ModelState.IsValid)
        {
            if (index >= 0 && index < _people.Count)
            {
                var person = _people[index];
                person.FirstName = model.FirstName;
                person.LastName = model.LastName;
                person.Gender = model.Gender;
                person.DateOfBirth = model.DateOfBirth;
                person.PhoneNumber = model.PhoneNumber;
                person.BirthPlace = model.BirthPlace;

                _people[index] = person;
            }

            return RedirectToAction("Index");
        }

        return View(model);
    }

    [HttpPost]
    public IActionResult Delete(int index)
    {
        if (index >= 0 && index < _people.Count)
        {
            _people.RemoveAt(index);
        }

        return RedirectToAction("Index");
    }
}

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Views/Rookies/Create.cshtml
@model PersonCreateModel

@{
    ViewData["Title"] = "Create new person";
}

<div class="row">
    <h1 class="display-4 text-center">Create new person</h1>
    <form asp-controller="Rookies" asp-action="Create" method="post" class="col-8 offset-2">
        <div class="form-group">
            <label asp-for="FirstName" class="mb-1"></label>
            <input asp-for="FirstName" type="text" class="form-control" placeholder="Enter your first name">
            <span asp-validation-for="FirstName" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LastName" class="mb-1"></label>
            <input asp-for="LastName" type="text" class="form-control" placeholder="Enter your last name">
            <span asp-validation-for="LastName" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="Gender" class="mb-1"></label>
            <select class="form-control" asp-for="Gender">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Others">Others</option>
            </select>
        </div>
        <div class="form-group mt-3">
            <label asp-for="DateOfBirth" class="mb-1"></label>
            <input asp-for="DateOfBirth" type="date" class="form-control" placeholder="Enter your date of birth">
            <span asp-validation-for="DateOfBirth" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="PhoneNumber" class="mb-1"></label>
            <input asp-for="PhoneNumber" type="text" class="form-control" placeholder="Enter your phone number">
            <span asp-validation-for="PhoneNumber" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="BirthPlace" class="mb-1"></label>
            <input asp-for="BirthPlace" type="text" class="form-control" placeholder="Enter your birth place">
            <span asp-validation-for="BirthPlace" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-danger" role="button" asp-controller="Rookies" asp-action="Index">Cancel</a>
        </div>
    </form>
</div>

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Views/Rookies/Edit.cshtml
@model PersonUpdateModel

@{
    ViewData["Title"] = "Update person info";
    var value = ViewData["Index"]?.ToString() ?? "";
    var index = !string.IsNullOrEmpty(value) ? int.Parse(value) : 0;
}

<div class="row">
    <h1 class="display-4 text-center">Update person info</h1>
    <form asp-controller="Rookies" asp-action="Update" asp-route-index="@index" method="post" class="col-8 offset-2">
        <div class="form-group">
            <label asp-for="FirstName" class="mb-1"></label>
            <input asp-for="FirstName" type="text" class="form-control" placeholder="Enter your first name">
            <span asp-validation-for="FirstName" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LastName" class="mb-1"></label>
            <input asp-for="LastName" type="text" class="form-control" placeholder="Enter your last name">
            <span asp-validation-for="LastName" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="Gender" class="mb-1"></label>
            <select class="form-control" asp-for="Gender">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Others">Others</option>
            </select>
        </div>
        <div class="form-group mt-3">
            <label asp-for="DateOfBirth" class="mb-1"></label>
            <input asp-for="DateOfBirth" type="date" class="form-control" placeholder="Enter your date of birth">
            <span asp-validation-for="DateOfBirth" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="PhoneNumber" class="mb-1"></label>
            <input asp-for="PhoneNumber" type="text" class="form-control" placeholder="Enter your phone number">
            <span asp-validation-for="PhoneNumber" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="BirthPlace" class="mb-1"></label>
            <input asp-for="BirthPlace" type="text" class="form-control" placeholder="Enter your birth place">
            <span asp-validation-for="BirthPlace" class="form-text text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-danger" role="button" asp-controller="Rookies" asp-action="Index">Cancel</a>
        </div>
    </form>
</div>

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Views/Rookies/Index.cshtml
@model List<PersonModel>

@{
    ViewData["Title"] = "Rookies Page";
}

<h1 class="display-4 text-center">Rookies List</h1>
<div class="text-left mt-3 mb-3">
    <a class="btn btn-success" role="button" asp-controller="Rookies" asp-action="Create">Create new person</a>
</div>
<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col" class="text-right">#</th>
                <th scope="col" class="text-left">Full Name</th>
                <th scope="col">Gender</th>
                <th scope="col">Date of Birth</th>
                <th scope="col">Birth Place</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                var person = Model[i];
                <tr>
                    <th scope="row" class="text-right">@(i + 1)</th>
                    <td class="text-left">@person.FullName</td>
                    <td>@person.Gender</td>
                    <td>@person.DateOfBirth.ToString("dd/MM/yyyy")</td>
                    <td>@person.BirthPlace</td>
                    <td>
                        <a class="btn btn-primary btn-sm mr-2" role="button" asp-controller="Rookies" asp-action="Edit"
                        asp-route-index="@i">Edit</a>
                        <a class="btn btn-danger btn-sm mr-2" role="button" data-bs-toggle="modal"
                        data-bs-target="#exampleModal_@i">Delete</a>

                        <div class="modal fade" id="exampleModal_@i" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form asp-controller="Rookies" asp-action="Delete" asp-route-index="@i" method="post"
                                    class="col-8 offset-2">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete this person?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Confirm</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

AspNetCoreMVC/AspNetCoreMVC_Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreMVC_Assignment2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetCoreMVC_Assignment2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreMVC_Assignment2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AspNetCoreMVC_Assignment2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>